# Site settings
title: The Stack
email: news@scyted.tv
description: > # this means to ignore newlines until next key
  A regular news show about pop culture, anime, gaming, and topics we find interesting!
meta_description: > # shortened description for meta description tag
  A regular news show about pop culture, anime, gaming, and topics we find interesting!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://news.scyted.tv" # the base hostname & protocol for your site
image_url: /img/posts # corresponds to directory for post images (cf. https://github.com/opattison/jekyll-figure-image-tag#why-yaml-is-useful-for-storing-images)
twitter_username: ScytedTV News
github_username: 
application: ""

# Defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: post
      displayed: Yes

# Outputting
permalink: pretty # don't have `.html` on the end of permalinks
timezone: America/Los_Angeles
paginate: 12 # items per page
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax

# plugins
plugins: [jekyll-paginate]
